name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: init ssh, deploy
      with:
          host: ${{ secrets.SERVER_IP }} 
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_PRIV_KEY }}
          script: |
            cd /home/lighthouse/wangguohui/wangguohui.cn
            ls
